# Form implementation generated from reading ui file 'c:\Users\Italo\OneDrive\reponoDesktop\tl_position.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 200)
        Form.setMaximumSize(QtCore.QSize(300, 200))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fr_primario = QtWidgets.QFrame(parent=Form)
        self.fr_primario.setMinimumSize(QtCore.QSize(300, 200))
        self.fr_primario.setMaximumSize(QtCore.QSize(300, 200))
        self.fr_primario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fr_primario.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_primario.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_primario.setObjectName("fr_primario")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fr_primario)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr_label = QtWidgets.QFrame(parent=self.fr_primario)
        self.fr_label.setMinimumSize(QtCore.QSize(300, 0))
        self.fr_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.fr_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fr_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_label.setObjectName("fr_label")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_label)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.fr_label)
        self.label.setMinimumSize(QtCore.QSize(250, 0))
        self.label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label.setStyleSheet("font: 12pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.fr_label)
        self.fr_entuser = QtWidgets.QFrame(parent=self.fr_primario)
        self.fr_entuser.setMinimumSize(QtCore.QSize(300, 0))
        self.fr_entuser.setMaximumSize(QtCore.QSize(300, 66))
        self.fr_entuser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fr_entuser.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_entuser.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_entuser.setObjectName("fr_entuser")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fr_entuser)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ent_position = QtWidgets.QLineEdit(parent=self.fr_entuser)
        self.ent_position.setMinimumSize(QtCore.QSize(0, 30))
        self.ent_position.setMaximumSize(QtCore.QSize(150, 40))
        self.ent_position.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.ent_position.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_position.setObjectName("ent_position")
        self.horizontalLayout_2.addWidget(self.ent_position)
        self.verticalLayout.addWidget(self.fr_entuser)
        self.fr_botton = QtWidgets.QFrame(parent=self.fr_primario)
        self.fr_botton.setMinimumSize(QtCore.QSize(300, 66))
        self.fr_botton.setMaximumSize(QtCore.QSize(300, 66))
        self.fr_botton.setStyleSheet("background-color: #FFFFFF;")
        self.fr_botton.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_botton.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_botton.setObjectName("fr_botton")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_botton)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_remover = QtWidgets.QPushButton(parent=self.fr_botton)
        self.bt_remover.setMaximumSize(QtCore.QSize(100, 30))
        self.bt_remover.setStyleSheet("QPushButton {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 120, 120);\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 100, 100);\n"
"}\n"
"")
        self.bt_remover.setObjectName("bt_remover")
        self.horizontalLayout.addWidget(self.bt_remover)
        self.verticalLayout.addWidget(self.fr_botton)
        self.verticalLayout_2.addWidget(self.fr_primario)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Digite a posição do produto na compra:"))
        self.bt_remover.setText(_translate("Form", "Remover"))
