# Form implementation generated from reading ui file 'c:\Users\Italo\OneDrive\reponoDesktop\widgets\tl_tabelaprodutos.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 439)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_10 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_10.setGeometry(QtCore.QRect(0, 10, 811, 381))
        self.widget_10.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"border-radius:10px;")
        self.widget_10.setObjectName("widget_10")
        self.table_tabela = QtWidgets.QTableWidget(parent=self.widget_10)
        self.table_tabela.setGeometry(QtCore.QRect(10, 10, 791, 361))
        self.table_tabela.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12px \"Arial\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;")
        self.table_tabela.setObjectName("table_tabela")
        self.table_tabela.setColumnCount(3)
        self.table_tabela.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_tabela.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tabela.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tabela.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table_tabela.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_tabela.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOME"))
        item = self.table_tabela.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DESCRIÇÃO"))
