# Form implementation generated from reading ui file 'c:\Users\Italo\OneDrive\reponoDesktop\widgets\tl_pro.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(990, 410)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, -3, 991, 511))
        self.frame.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.bt_cadas = QtWidgets.QPushButton(parent=self.frame)
        self.bt_cadas.setGeometry(QtCore.QRect(30, 360, 150, 35))
        self.bt_cadas.setMinimumSize(QtCore.QSize(150, 35))
        self.bt_cadas.setMaximumSize(QtCore.QSize(100, 30))
        self.bt_cadas.setStyleSheet("\n"
"QPushButton {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.bt_cadas.setObjectName("bt_cadas")
        self.bt_con = QtWidgets.QPushButton(parent=self.frame)
        self.bt_con.setGeometry(QtCore.QRect(220, 360, 150, 35))
        self.bt_con.setMinimumSize(QtCore.QSize(150, 35))
        self.bt_con.setMaximumSize(QtCore.QSize(100, 30))
        self.bt_con.setStyleSheet("\n"
"QPushButton {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.bt_con.setObjectName("bt_con")
        self.bt_remover = QtWidgets.QPushButton(parent=self.frame)
        self.bt_remover.setGeometry(QtCore.QRect(410, 360, 150, 35))
        self.bt_remover.setMinimumSize(QtCore.QSize(150, 35))
        self.bt_remover.setMaximumSize(QtCore.QSize(100, 30))
        self.bt_remover.setStyleSheet("\n"
"QPushButton {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.bt_remover.setObjectName("bt_remover")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(-30, 204, 231, 21))
        self.label_2.setStyleSheet("font: 81 8pt \"Rockwell Extra Bold\";\n"
"font: 63 14pt \"Open Sans Semibold\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(180, 0, 601, 81))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 81 8pt \"Rockwell Extra Bold\";\n"
"font: 63 14pt \"Open Sans Semibold\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(460, 124, 231, 21))
        self.label_5.setStyleSheet("font: 81 8pt \"Rockwell Extra Bold\";\n"
"font: 63 14pt \"Open Sans Semibold\";")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(460, 204, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 81 8pt \"Rockwell Extra Bold\";\n"
"font: 63 14pt \"Open Sans Semibold\";")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setGeometry(QtCore.QRect(-30, 124, 231, 21))
        self.label_8.setStyleSheet("font: 81 8pt \"Rockwell Extra Bold\";\n"
"font: 63 14pt \"Open Sans Semibold\";")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.bt_atualizar = QtWidgets.QPushButton(parent=self.frame)
        self.bt_atualizar.setGeometry(QtCore.QRect(600, 360, 150, 35))
        self.bt_atualizar.setMinimumSize(QtCore.QSize(150, 35))
        self.bt_atualizar.setMaximumSize(QtCore.QSize(100, 30))
        self.bt_atualizar.setStyleSheet("\n"
"QPushButton {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.bt_atualizar.setObjectName("bt_atualizar")
        self.bt_limpar = QtWidgets.QPushButton(parent=self.frame)
        self.bt_limpar.setGeometry(QtCore.QRect(790, 360, 150, 35))
        self.bt_limpar.setMinimumSize(QtCore.QSize(150, 35))
        self.bt_limpar.setMaximumSize(QtCore.QSize(1000, 30))
        self.bt_limpar.setStyleSheet("\n"
"QPushButton {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.bt_limpar.setObjectName("bt_limpar")
        self.label_9 = QtWidgets.QLabel(parent=self.frame)
        self.label_9.setGeometry(QtCore.QRect(-28, 285, 231, 21))
        self.label_9.setStyleSheet("font: 81 8pt \"Rockwell Extra Bold\";\n"
"font: 63 14pt \"Open Sans Semibold\";")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        self.label_10.setGeometry(QtCore.QRect(450, 285, 231, 21))
        self.label_10.setStyleSheet("font: 81 8pt \"Rockwell Extra Bold\";\n"
"font: 63 14pt \"Open Sans Semibold\";")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.ent_id = QtWidgets.QLineEdit(parent=self.frame)
        self.ent_id.setGeometry(QtCore.QRect(162, 120, 291, 31))
        self.ent_id.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.ent_id.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_id.setObjectName("ent_id")
        self.ent_prodt = QtWidgets.QLineEdit(parent=self.frame)
        self.ent_prodt.setGeometry(QtCore.QRect(160, 200, 291, 31))
        self.ent_prodt.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.ent_prodt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_prodt.setObjectName("ent_prodt")
        self.ent_est = QtWidgets.QLineEdit(parent=self.frame)
        self.ent_est.setGeometry(QtCore.QRect(160, 280, 291, 31))
        self.ent_est.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.ent_est.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_est.setObjectName("ent_est")
        self.ent_vldc = QtWidgets.QLineEdit(parent=self.frame)
        self.ent_vldc.setGeometry(QtCore.QRect(670, 120, 291, 31))
        self.ent_vldc.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.ent_vldc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_vldc.setObjectName("ent_vldc")
        self.ent_vldv = QtWidgets.QLineEdit(parent=self.frame)
        self.ent_vldv.setGeometry(QtCore.QRect(670, 200, 291, 31))
        self.ent_vldv.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.ent_vldv.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_vldv.setObjectName("ent_vldv")
        self.ent_des = QtWidgets.QLineEdit(parent=self.frame)
        self.ent_des.setGeometry(QtCore.QRect(670, 280, 291, 31))
        self.ent_des.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.ent_des.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_des.setObjectName("ent_des")
        self.label_9.raise_()
        self.bt_cadas.raise_()
        self.bt_con.raise_()
        self.bt_remover.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.bt_atualizar.raise_()
        self.bt_limpar.raise_()
        self.label_10.raise_()
        self.ent_id.raise_()
        self.ent_prodt.raise_()
        self.ent_est.raise_()
        self.ent_vldc.raise_()
        self.ent_vldv.raise_()
        self.ent_des.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_cadas.setText(_translate("Form", "Cadastrar"))
        self.bt_con.setText(_translate("Form", "Consultar"))
        self.bt_remover.setText(_translate("Form", "Remover"))
        self.label_2.setText(_translate("Form", "Produtos"))
        self.label_3.setText(_translate("Form", "Produtos "))
        self.label_5.setText(_translate("Form", "Valor Da Compra "))
        self.label_6.setText(_translate("Form", "Valor Da Venda"))
        self.label_8.setText(_translate("Form", "Id"))
        self.bt_atualizar.setText(_translate("Form", "Atualizar"))
        self.bt_limpar.setText(_translate("Form", "Limpa Campos"))
        self.label_9.setText(_translate("Form", "Estoque"))
        self.label_10.setText(_translate("Form", "Descrição"))
