# Form implementation generated from reading ui file 'c:\Users\Italo\OneDrive\reponoDesktop\widgets\tl_caixa.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 458)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_11 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_11.setGeometry(QtCore.QRect(0, 40, 811, 381))
        self.widget_11.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"border-radius:10px;")
        self.widget_11.setObjectName("widget_11")
        self.table_caixa = QtWidgets.QTableWidget(parent=self.widget_11)
        self.table_caixa.setGeometry(QtCore.QRect(420, 20, 381, 281))
        self.table_caixa.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12px \"Arial\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: black;")
        self.table_caixa.setObjectName("table_caixa")
        self.table_caixa.setColumnCount(4)
        self.table_caixa.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_caixa.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_caixa.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_caixa.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_caixa.setHorizontalHeaderItem(3, item)
        self.bt_sair = QtWidgets.QPushButton(parent=self.widget_11)
        self.bt_sair.setGeometry(QtCore.QRect(714, 340, 81, 31))
        self.bt_sair.setStyleSheet("QPushButton {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(225, 0, 3);\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(200, 0, 0);\n"
"}\n"
"")
        self.bt_sair.setObjectName("bt_sair")
        self.bt_finalizarcompra = QtWidgets.QPushButton(parent=self.widget_11)
        self.bt_finalizarcompra.setGeometry(QtCore.QRect(490, 340, 101, 31))
        self.bt_finalizarcompra.setStyleSheet("QPushButton {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(223, 226, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(182, 185, 0);\n"
"}\n"
"")
        self.bt_finalizarcompra.setObjectName("bt_finalizarcompra")
        self.bt_cancelarcompra = QtWidgets.QPushButton(parent=self.widget_11)
        self.bt_cancelarcompra.setGeometry(QtCore.QRect(380, 340, 101, 31))
        self.bt_cancelarcompra.setStyleSheet("QPushButton {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 120, 120);\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 100, 100);\n"
"}\n"
"")
        self.bt_cancelarcompra.setObjectName("bt_cancelarcompra")
        self.bt_cancelarproduto = QtWidgets.QPushButton(parent=self.widget_11)
        self.bt_cancelarproduto.setGeometry(QtCore.QRect(270, 340, 101, 31))
        self.bt_cancelarproduto.setStyleSheet("QPushButton {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(120, 120, 120);\n"
"}\n"
"QPushButton:pressed {\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 100, 100);\n"
"}\n"
"")
        self.bt_cancelarproduto.setObjectName("bt_cancelarproduto")
        self.label_14 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 31, 31))
        self.label_14.setObjectName("label_14")
        self.ent_idcaixa = QtWidgets.QLineEdit(parent=self.widget_11)
        self.ent_idcaixa.setGeometry(QtCore.QRect(50, 70, 61, 51))
        self.ent_idcaixa.setMinimumSize(QtCore.QSize(50, 20))
        self.ent_idcaixa.setMaximumSize(QtCore.QSize(400, 16777215))
        self.ent_idcaixa.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ent_idcaixa.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_idcaixa.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ent_idcaixa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_idcaixa.setObjectName("ent_idcaixa")
        self.label_15 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_15.setGeometry(QtCore.QRect(130, 80, 91, 31))
        self.label_15.setObjectName("label_15")
        self.ent_produtocaixa = QtWidgets.QLineEdit(parent=self.widget_11)
        self.ent_produtocaixa.setGeometry(QtCore.QRect(230, 70, 181, 51))
        self.ent_produtocaixa.setMinimumSize(QtCore.QSize(50, 20))
        self.ent_produtocaixa.setMaximumSize(QtCore.QSize(400, 16777215))
        self.ent_produtocaixa.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ent_produtocaixa.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_produtocaixa.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ent_produtocaixa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_produtocaixa.setObjectName("ent_produtocaixa")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_16.setGeometry(QtCore.QRect(260, 160, 41, 31))
        self.label_16.setObjectName("label_16")
        self.ent_qtcaixa = QtWidgets.QLineEdit(parent=self.widget_11)
        self.ent_qtcaixa.setGeometry(QtCore.QRect(310, 150, 61, 51))
        self.ent_qtcaixa.setMinimumSize(QtCore.QSize(50, 20))
        self.ent_qtcaixa.setMaximumSize(QtCore.QSize(400, 16777215))
        self.ent_qtcaixa.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ent_qtcaixa.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_qtcaixa.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ent_qtcaixa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_qtcaixa.setObjectName("ent_qtcaixa")
        self.label_17 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_17.setGeometry(QtCore.QRect(10, 160, 111, 31))
        self.label_17.setObjectName("label_17")
        self.ent_valorcaixa = QtWidgets.QLineEdit(parent=self.widget_11)
        self.ent_valorcaixa.setGeometry(QtCore.QRect(130, 150, 111, 51))
        self.ent_valorcaixa.setMinimumSize(QtCore.QSize(50, 20))
        self.ent_valorcaixa.setMaximumSize(QtCore.QSize(400, 16777215))
        self.ent_valorcaixa.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ent_valorcaixa.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_valorcaixa.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ent_valorcaixa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_valorcaixa.setObjectName("ent_valorcaixa")
        self.label_18 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_18.setGeometry(QtCore.QRect(10, 250, 91, 31))
        self.label_18.setObjectName("label_18")
        self.ent_subtotalcaixa = QtWidgets.QLineEdit(parent=self.widget_11)
        self.ent_subtotalcaixa.setGeometry(QtCore.QRect(120, 240, 121, 51))
        self.ent_subtotalcaixa.setMinimumSize(QtCore.QSize(50, 20))
        self.ent_subtotalcaixa.setMaximumSize(QtCore.QSize(400, 16777215))
        self.ent_subtotalcaixa.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ent_subtotalcaixa.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_subtotalcaixa.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ent_subtotalcaixa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_subtotalcaixa.setObjectName("ent_subtotalcaixa")
        self.label_19 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.label_19.setObjectName("label_19")
        self.ent_atendente = QtWidgets.QLineEdit(parent=self.widget_11)
        self.ent_atendente.setGeometry(QtCore.QRect(130, 10, 141, 31))
        self.ent_atendente.setMinimumSize(QtCore.QSize(50, 20))
        self.ent_atendente.setMaximumSize(QtCore.QSize(400, 16777215))
        self.ent_atendente.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ent_atendente.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_atendente.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ent_atendente.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ent_atendente.setObjectName("ent_atendente")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table_caixa.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_caixa.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOME"))
        item = self.table_caixa.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "QT"))
        item = self.table_caixa.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "VALOR"))
        self.bt_sair.setText(_translate("MainWindow", "Sair"))
        self.bt_finalizarcompra.setText(_translate("MainWindow", "Finalizar"))
        self.bt_cancelarcompra.setText(_translate("MainWindow", "Can.Comp"))
        self.bt_cancelarproduto.setText(_translate("MainWindow", "Can.Prod"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">ID</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Produto</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">QT</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Valor Unit.</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Subtotal</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Atendente</span></p></body></html>"))
