# Form implementation generated from reading ui file 'c:\Users\Italo\OneDrive\reponoDesktop\widgets\tl_cadasfuncionarios.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fr_funcionarios = QtWidgets.QWidget(parent=self.centralwidget)
        self.fr_funcionarios.setGeometry(QtCore.QRect(10, 70, 801, 381))
        self.fr_funcionarios.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"border-radius:10px;")
        self.fr_funcionarios.setObjectName("fr_funcionarios")
        self.label_13 = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 231, 21))
        self.label_13.setObjectName("label_13")
        self.ent_id = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_id.setGeometry(QtCore.QRect(40, 70, 91, 41))
        self.ent_id.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_id.setObjectName("ent_id")
        self.label_id = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_id.setGeometry(QtCore.QRect(10, 80, 21, 21))
        self.label_id.setObjectName("label_id")
        self.ent_nome = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_nome.setGeometry(QtCore.QRect(210, 70, 431, 41))
        self.ent_nome.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_nome.setObjectName("ent_nome")
        self.ent_nascimento = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_nascimento.setGeometry(QtCore.QRect(200, 130, 131, 41))
        self.ent_nascimento.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_nascimento.setObjectName("ent_nascimento")
        self.label_nome = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_nome.setGeometry(QtCore.QRect(150, 80, 61, 21))
        self.label_nome.setObjectName("label_nome")
        self.label_contato = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_contato.setGeometry(QtCore.QRect(10, 200, 81, 20))
        self.label_contato.setObjectName("label_contato")
        self.label_nascimento = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_nascimento.setGeometry(QtCore.QRect(10, 140, 181, 16))
        self.label_nascimento.setObjectName("label_nascimento")
        self.label_cpf = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_cpf.setGeometry(QtCore.QRect(350, 140, 47, 16))
        self.label_cpf.setObjectName("label_cpf")
        self.label_email = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_email.setGeometry(QtCore.QRect(240, 200, 51, 21))
        self.label_email.setObjectName("label_email")
        self.label_senha = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_senha.setGeometry(QtCore.QRect(290, 260, 61, 21))
        self.label_senha.setObjectName("label_senha")
        self.label_usuario = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_usuario.setGeometry(QtCore.QRect(10, 260, 71, 16))
        self.label_usuario.setObjectName("label_usuario")
        self.ent_cpf = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_cpf.setGeometry(QtCore.QRect(390, 130, 141, 41))
        self.ent_cpf.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_cpf.setObjectName("ent_cpf")
        self.ent_contato = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_contato.setGeometry(QtCore.QRect(90, 190, 131, 41))
        self.ent_contato.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_contato.setObjectName("ent_contato")
        self.ent_email = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_email.setGeometry(QtCore.QRect(300, 190, 341, 41))
        self.ent_email.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_email.setObjectName("ent_email")
        self.ent_senha = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_senha.setGeometry(QtCore.QRect(350, 250, 113, 41))
        self.ent_senha.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_senha.setObjectName("ent_senha")
        self.ent_usuario = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_usuario.setGeometry(QtCore.QRect(90, 250, 171, 41))
        self.ent_usuario.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_usuario.setObjectName("ent_usuario")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_13.setText(_translate("MainWindow", "Cadastro de Funcionários"))
        self.label_id.setText(_translate("MainWindow", "ID"))
        self.ent_nascimento.setInputMask(_translate("MainWindow", "99/99/9999"))
        self.label_nome.setText(_translate("MainWindow", "Nome"))
        self.label_contato.setText(_translate("MainWindow", "Contato"))
        self.label_nascimento.setText(_translate("MainWindow", "Data de Nascimento"))
        self.label_cpf.setText(_translate("MainWindow", "CPF"))
        self.label_email.setText(_translate("MainWindow", "Email"))
        self.label_senha.setText(_translate("MainWindow", "Senha"))
        self.label_usuario.setText(_translate("MainWindow", "Usuário"))
        self.ent_cpf.setInputMask(_translate("MainWindow", "999.999.999-99"))
        self.ent_contato.setInputMask(_translate("MainWindow", "(99)99999-9999"))
