# Form implementation generated from reading ui file 'c:\Users\Italo\OneDrive\reponoDesktop\widgets\tl_pessoas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1630, 828)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fr_fornecedores = QtWidgets.QWidget(parent=self.centralwidget)
        self.fr_fornecedores.setGeometry(QtCore.QRect(10, 0, 801, 381))
        self.fr_fornecedores.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"border-radius:10px;")
        self.fr_fornecedores.setObjectName("fr_fornecedores")
        self.label_14 = QtWidgets.QLabel(parent=self.fr_fornecedores)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 261, 21))
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(parent=self.fr_fornecedores)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 31, 21))
        self.label_16.setObjectName("label_16")
        self.ent_id_forne = QtWidgets.QLineEdit(parent=self.fr_fornecedores)
        self.ent_id_forne.setGeometry(QtCore.QRect(50, 70, 71, 41))
        self.ent_id_forne.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_id_forne.setObjectName("ent_id_forne")
        self.label_17 = QtWidgets.QLabel(parent=self.fr_fornecedores)
        self.label_17.setGeometry(QtCore.QRect(150, 80, 61, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.fr_fornecedores)
        self.label_18.setGeometry(QtCore.QRect(10, 140, 51, 16))
        self.label_18.setObjectName("label_18")
        self.ent_email_forne = QtWidgets.QLineEdit(parent=self.fr_fornecedores)
        self.ent_email_forne.setGeometry(QtCore.QRect(70, 130, 351, 41))
        self.ent_email_forne.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_email_forne.setObjectName("ent_email_forne")
        self.label_19 = QtWidgets.QLabel(parent=self.fr_fornecedores)
        self.label_19.setGeometry(QtCore.QRect(440, 140, 81, 16))
        self.label_19.setObjectName("label_19")
        self.ent_telefone_forne = QtWidgets.QLineEdit(parent=self.fr_fornecedores)
        self.ent_telefone_forne.setGeometry(QtCore.QRect(530, 130, 181, 41))
        self.ent_telefone_forne.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_telefone_forne.setObjectName("ent_telefone_forne")
        self.label_20 = QtWidgets.QLabel(parent=self.fr_fornecedores)
        self.label_20.setGeometry(QtCore.QRect(10, 200, 51, 16))
        self.label_20.setObjectName("label_20")
        self.ent_cnpj_forne = QtWidgets.QLineEdit(parent=self.fr_fornecedores)
        self.ent_cnpj_forne.setGeometry(QtCore.QRect(70, 190, 181, 41))
        self.ent_cnpj_forne.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_cnpj_forne.setObjectName("ent_cnpj_forne")
        self.ent_nome_forne = QtWidgets.QLineEdit(parent=self.fr_fornecedores)
        self.ent_nome_forne.setGeometry(QtCore.QRect(210, 70, 431, 41))
        self.ent_nome_forne.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_nome_forne.setObjectName("ent_nome_forne")
        self.fr_clientes = QtWidgets.QWidget(parent=self.centralwidget)
        self.fr_clientes.setGeometry(QtCore.QRect(10, 390, 801, 381))
        self.fr_clientes.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"border-radius:10px;")
        self.fr_clientes.setObjectName("fr_clientes")
        self.label_15 = QtWidgets.QLabel(parent=self.fr_clientes)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 201, 21))
        self.label_15.setObjectName("label_15")
        self.label_idC = QtWidgets.QLabel(parent=self.fr_clientes)
        self.label_idC.setGeometry(QtCore.QRect(10, 100, 31, 16))
        self.label_idC.setObjectName("label_idC")
        self.ent_id_clientes = QtWidgets.QLineEdit(parent=self.fr_clientes)
        self.ent_id_clientes.setGeometry(QtCore.QRect(40, 90, 71, 41))
        self.ent_id_clientes.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_id_clientes.setObjectName("ent_id_clientes")
        self.label_nomeC = QtWidgets.QLabel(parent=self.fr_clientes)
        self.label_nomeC.setGeometry(QtCore.QRect(140, 100, 61, 16))
        self.label_nomeC.setObjectName("label_nomeC")
        self.ent_nome_clientes = QtWidgets.QLineEdit(parent=self.fr_clientes)
        self.ent_nome_clientes.setGeometry(QtCore.QRect(200, 90, 431, 41))
        self.ent_nome_clientes.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_nome_clientes.setObjectName("ent_nome_clientes")
        self.label_cpfC = QtWidgets.QLabel(parent=self.fr_clientes)
        self.label_cpfC.setGeometry(QtCore.QRect(10, 170, 41, 21))
        self.label_cpfC.setObjectName("label_cpfC")
        self.ent_cpf_clientes = QtWidgets.QLineEdit(parent=self.fr_clientes)
        self.ent_cpf_clientes.setGeometry(QtCore.QRect(50, 160, 131, 41))
        self.ent_cpf_clientes.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_cpf_clientes.setObjectName("ent_cpf_clientes")
        self.label_dt_nascimentoC = QtWidgets.QLabel(parent=self.fr_clientes)
        self.label_dt_nascimentoC.setGeometry(QtCore.QRect(200, 170, 181, 16))
        self.label_dt_nascimentoC.setObjectName("label_dt_nascimentoC")
        self.ent_dt_nascimento = QtWidgets.QLineEdit(parent=self.fr_clientes)
        self.ent_dt_nascimento.setGeometry(QtCore.QRect(400, 160, 131, 41))
        self.ent_dt_nascimento.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_dt_nascimento.setObjectName("ent_dt_nascimento")
        self.label_contatoC = QtWidgets.QLabel(parent=self.fr_clientes)
        self.label_contatoC.setGeometry(QtCore.QRect(10, 230, 81, 16))
        self.label_contatoC.setObjectName("label_contatoC")
        self.ent_contato_clientes = QtWidgets.QLineEdit(parent=self.fr_clientes)
        self.ent_contato_clientes.setGeometry(QtCore.QRect(90, 220, 131, 41))
        self.ent_contato_clientes.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_contato_clientes.setObjectName("ent_contato_clientes")
        self.label_emailC = QtWidgets.QLabel(parent=self.fr_clientes)
        self.label_emailC.setGeometry(QtCore.QRect(240, 230, 51, 16))
        self.label_emailC.setObjectName("label_emailC")
        self.ent_email_clientes = QtWidgets.QLineEdit(parent=self.fr_clientes)
        self.ent_email_clientes.setGeometry(QtCore.QRect(300, 220, 361, 41))
        self.ent_email_clientes.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_email_clientes.setObjectName("ent_email_clientes")
        self.fr_funcionarios = QtWidgets.QWidget(parent=self.centralwidget)
        self.fr_funcionarios.setGeometry(QtCore.QRect(820, 0, 801, 381))
        self.fr_funcionarios.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"border-radius:10px;")
        self.fr_funcionarios.setObjectName("fr_funcionarios")
        self.label_13 = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 231, 21))
        self.label_13.setObjectName("label_13")
        self.ent_id = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_id.setGeometry(QtCore.QRect(40, 70, 71, 41))
        self.ent_id.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_id.setObjectName("ent_id")
        self.label_id = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_id.setGeometry(QtCore.QRect(10, 80, 21, 21))
        self.label_id.setObjectName("label_id")
        self.ent_nome = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_nome.setGeometry(QtCore.QRect(200, 70, 431, 41))
        self.ent_nome.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_nome.setObjectName("ent_nome")
        self.ent_nascimento = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_nascimento.setGeometry(QtCore.QRect(200, 130, 131, 41))
        self.ent_nascimento.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_nascimento.setObjectName("ent_nascimento")
        self.label_nome = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_nome.setGeometry(QtCore.QRect(140, 80, 61, 21))
        self.label_nome.setObjectName("label_nome")
        self.label_contato = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_contato.setGeometry(QtCore.QRect(10, 200, 81, 20))
        self.label_contato.setObjectName("label_contato")
        self.label_nascimento = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_nascimento.setGeometry(QtCore.QRect(10, 140, 181, 16))
        self.label_nascimento.setObjectName("label_nascimento")
        self.label_cpf = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_cpf.setGeometry(QtCore.QRect(350, 140, 47, 16))
        self.label_cpf.setObjectName("label_cpf")
        self.label_email = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_email.setGeometry(QtCore.QRect(240, 200, 51, 21))
        self.label_email.setObjectName("label_email")
        self.label_senha = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_senha.setGeometry(QtCore.QRect(290, 260, 61, 21))
        self.label_senha.setObjectName("label_senha")
        self.label_usuario = QtWidgets.QLabel(parent=self.fr_funcionarios)
        self.label_usuario.setGeometry(QtCore.QRect(10, 260, 71, 16))
        self.label_usuario.setObjectName("label_usuario")
        self.ent_cpf = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_cpf.setGeometry(QtCore.QRect(390, 130, 141, 41))
        self.ent_cpf.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_cpf.setObjectName("ent_cpf")
        self.ent_contato = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_contato.setGeometry(QtCore.QRect(90, 190, 131, 41))
        self.ent_contato.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_contato.setObjectName("ent_contato")
        self.ent_email = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_email.setGeometry(QtCore.QRect(300, 190, 341, 41))
        self.ent_email.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_email.setObjectName("ent_email")
        self.ent_senha = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_senha.setGeometry(QtCore.QRect(350, 250, 113, 41))
        self.ent_senha.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_senha.setObjectName("ent_senha")
        self.ent_usuario = QtWidgets.QLineEdit(parent=self.fr_funcionarios)
        self.ent_usuario.setGeometry(QtCore.QRect(90, 250, 171, 41))
        self.ent_usuario.setStyleSheet("QLineEdit {\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: 87 12pt \"Segoe UI Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ent_usuario.setObjectName("ent_usuario")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1630, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_14.setText(_translate("MainWindow", "Cadastro de Fornecedores"))
        self.label_16.setText(_translate("MainWindow", "ID"))
        self.label_17.setText(_translate("MainWindow", "Nome"))
        self.label_18.setText(_translate("MainWindow", "Email"))
        self.label_19.setText(_translate("MainWindow", "Telefone"))
        self.ent_telefone_forne.setInputMask(_translate("MainWindow", "(31)99999-9999"))
        self.label_20.setText(_translate("MainWindow", "CNPJ"))
        self.ent_cnpj_forne.setInputMask(_translate("MainWindow", "99.999.999/9999-99"))
        self.label_15.setText(_translate("MainWindow", "Cadastro de Clientes"))
        self.label_idC.setText(_translate("MainWindow", "ID"))
        self.label_nomeC.setText(_translate("MainWindow", "Nome"))
        self.label_cpfC.setText(_translate("MainWindow", "CPF"))
        self.ent_cpf_clientes.setInputMask(_translate("MainWindow", "999.999.999-99"))
        self.label_dt_nascimentoC.setText(_translate("MainWindow", "Data de Nascimento"))
        self.ent_dt_nascimento.setInputMask(_translate("MainWindow", "99/99/9999"))
        self.label_contatoC.setText(_translate("MainWindow", "Contato"))
        self.ent_contato_clientes.setInputMask(_translate("MainWindow", "(99)99999-9999"))
        self.label_emailC.setText(_translate("MainWindow", "Email"))
        self.label_13.setText(_translate("MainWindow", "Cadastro de Funcionários"))
        self.label_id.setText(_translate("MainWindow", "ID"))
        self.ent_nascimento.setInputMask(_translate("MainWindow", "99/99/9999"))
        self.label_nome.setText(_translate("MainWindow", "Nome"))
        self.label_contato.setText(_translate("MainWindow", "Contato"))
        self.label_nascimento.setText(_translate("MainWindow", "Data de Nascimento"))
        self.label_cpf.setText(_translate("MainWindow", "CPF"))
        self.label_email.setText(_translate("MainWindow", "Email"))
        self.label_senha.setText(_translate("MainWindow", "Senha"))
        self.label_usuario.setText(_translate("MainWindow", "Usuário"))
        self.ent_cpf.setInputMask(_translate("MainWindow", "999.999.999-99"))
        self.ent_contato.setInputMask(_translate("MainWindow", "(99)99999-9999"))
